# Generated by Django 4.2.4 on 2023-11-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('user', 'Пользователь')], default='user', max_length=15, verbose_name='права доступа'),
        ),
    ]
