# Generated by Django 4.2.4 on 2023-11-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления'),
        ),
    ]
