# Generated by Django 4.2.4 on 2023-11-09 04:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletin_board', '0004_alter_advertisement_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisement',
            new_name='Ad',
        ),
    ]
